//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskScheduler
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int ID { get; set; }
        public int IdentityID { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public int Phone { get; set; }
        public string Profession { get; set; }
        public System.DateTime RegistrationDate { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
        public string Status { get; set; }
    }
}
